# GET http://localhost:8088/api/auth/profile HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImRlcGFydG1lbnRJRCI6MSwiaXNNYW5hZ2VyIjp0cnVlLCJlbWFpbCI6bnVsbCwiaWF0IjoxNzA0MjQzODc4LCJleHAiOjE3MDQzMzAyNzh9.n0nhVaAJG_kXBrtCqeXaGKGdXjxEzKfVkCNdemzWDHo
# GET http://localhost:8088/api/ HTTP/1.1
# curl -X POST http://localhost:3000/auth/login -d '{"username": "john", "password": "changeme"}' -H "Content-Type: application/json"
# POST http://localhost:8088/api/auth/login HTTP/1.1
# content-type: application/json

# {
#     "username": "admin",
#     "password": "1234"
# }

# GET http://localhost:8088/api/category/all HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImRlcGFydG1lbnRJRCI6MSwiaXNNYW5hZ2VyIjp0cnVlLCJlbWFpbCI6bnVsbCwiaWF0IjoxNzA0MjQzODc4LCJleHAiOjE3MDQzMzAyNzh9.n0nhVaAJG_kXBrtCqeXaGKGdXjxEzKfVkCNdemzWDHo
GET http://localhost:8088/api/user/test HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1OEFDNUZCMy0wOEFBLUVFMTEtQTFDQS0wNEQ5RjVDOUQyRUIiLCJkZXBhcnRtZW50SUQiOiIxMzcwYTE2Yi0wOGFhLWVlMTEtYTFjYS0wNGQ5ZjVjOWQyZWIiLCJpc01hbmFnZXIiOmZhbHNlLCJlbWFpbCI6bnVsbCwiaWF0IjoxNzA0Njc2NzY2LCJleHAiOjE3MDQ3NjMxNjZ9.OLfWIeTP57iOjTtKjIuB8q7OG3lTsd6PTSO9LXbKsYw